services:
  - type: web
    name: sdlc-platform
    env: node
    region: singapore
    repo: https://github.com/Tran-Hai/Software-Development-Life-Cycle
    branch: main
    rootDir: packages/frontend
    buildCommand: npm install --legacy-peer-deps && npx prisma generate && npm run build
    startCommand: npm run start
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
